// Code generated by protoc-gen-go. DO NOT EDIT.
// source: describe.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DescribeLevel int32

const (
	DescribeLevel_BASIC      DescribeLevel = 0
	DescribeLevel_EVERYTHING DescribeLevel = 1
	DescribeLevel_CONFIG     DescribeLevel = 2
	DescribeLevel_NODES      DescribeLevel = 3
)

var DescribeLevel_name = map[int32]string{
	0: "BASIC",
	1: "EVERYTHING",
	2: "CONFIG",
	3: "NODES",
}

var DescribeLevel_value = map[string]int32{
	"BASIC":      0,
	"EVERYTHING": 1,
	"CONFIG":     2,
	"NODES":      3,
}

func (x DescribeLevel) String() string {
	return proto.EnumName(DescribeLevel_name, int32(x))
}

func (DescribeLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_257e39eedb50142f, []int{0}
}

type ClusterConfig struct {
	Variables            map[string]string `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources            []string          `protobuf:"bytes,6,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClusterConfig) Reset()         { *m = ClusterConfig{} }
func (m *ClusterConfig) String() string { return proto.CompactTextString(m) }
func (*ClusterConfig) ProtoMessage()    {}
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_257e39eedb50142f, []int{0}
}

func (m *ClusterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterConfig.Unmarshal(m, b)
}
func (m *ClusterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterConfig.Marshal(b, m, deterministic)
}
func (m *ClusterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConfig.Merge(m, src)
}
func (m *ClusterConfig) XXX_Size() int {
	return xxx_messageInfo_ClusterConfig.Size(m)
}
func (m *ClusterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConfig proto.InternalMessageInfo

func (m *ClusterConfig) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *ClusterConfig) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Node struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PoolName             string   `protobuf:"bytes,2,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	PublicIp             string   `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	PrivateIp            string   `protobuf:"bytes,5,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	OtherIps             []string `protobuf:"bytes,6,rep,name=other_ips,json=otherIps,proto3" json:"other_ips,omitempty"`
	PublicDns            string   `protobuf:"bytes,7,opt,name=public_dns,json=publicDns,proto3" json:"public_dns,omitempty"`
	PrivateDns           string   `protobuf:"bytes,8,opt,name=private_dns,json=privateDns,proto3" json:"private_dns,omitempty"`
	OtherDns             []string `protobuf:"bytes,9,rep,name=other_dns,json=otherDns,proto3" json:"other_dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_257e39eedb50142f, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *Node) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Node) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

func (m *Node) GetPrivateIp() string {
	if m != nil {
		return m.PrivateIp
	}
	return ""
}

func (m *Node) GetOtherIps() []string {
	if m != nil {
		return m.OtherIps
	}
	return nil
}

func (m *Node) GetPublicDns() string {
	if m != nil {
		return m.PublicDns
	}
	return ""
}

func (m *Node) GetPrivateDns() string {
	if m != nil {
		return m.PrivateDns
	}
	return ""
}

func (m *Node) GetOtherDns() []string {
	if m != nil {
		return m.OtherDns
	}
	return nil
}

type NodePool struct {
	PoolName             string   `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodePool) Reset()         { *m = NodePool{} }
func (m *NodePool) String() string { return proto.CompactTextString(m) }
func (*NodePool) ProtoMessage()    {}
func (*NodePool) Descriptor() ([]byte, []int) {
	return fileDescriptor_257e39eedb50142f, []int{2}
}

func (m *NodePool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodePool.Unmarshal(m, b)
}
func (m *NodePool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodePool.Marshal(b, m, deterministic)
}
func (m *NodePool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodePool.Merge(m, src)
}
func (m *NodePool) XXX_Size() int {
	return xxx_messageInfo_NodePool.Size(m)
}
func (m *NodePool) XXX_DiscardUnknown() {
	xxx_messageInfo_NodePool.DiscardUnknown(m)
}

var xxx_messageInfo_NodePool proto.InternalMessageInfo

func (m *NodePool) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *NodePool) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ClusterNodes struct {
	NodePools            []*NodePool `protobuf:"bytes,1,rep,name=node_pools,json=nodePools,proto3" json:"node_pools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClusterNodes) Reset()         { *m = ClusterNodes{} }
func (m *ClusterNodes) String() string { return proto.CompactTextString(m) }
func (*ClusterNodes) ProtoMessage()    {}
func (*ClusterNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_257e39eedb50142f, []int{3}
}

func (m *ClusterNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterNodes.Unmarshal(m, b)
}
func (m *ClusterNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterNodes.Marshal(b, m, deterministic)
}
func (m *ClusterNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterNodes.Merge(m, src)
}
func (m *ClusterNodes) XXX_Size() int {
	return xxx_messageInfo_ClusterNodes.Size(m)
}
func (m *ClusterNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterNodes.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterNodes proto.InternalMessageInfo

func (m *ClusterNodes) GetNodePools() []*NodePool {
	if m != nil {
		return m.NodePools
	}
	return nil
}

type DescribeRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ShowParams           []string `protobuf:"bytes,3,rep,name=show_params,json=showParams,proto3" json:"show_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeRequest) Reset()         { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()    {}
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_257e39eedb50142f, []int{4}
}

func (m *DescribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeRequest.Unmarshal(m, b)
}
func (m *DescribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeRequest.Marshal(b, m, deterministic)
}
func (m *DescribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeRequest.Merge(m, src)
}
func (m *DescribeRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeRequest.Size(m)
}
func (m *DescribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeRequest proto.InternalMessageInfo

func (m *DescribeRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DescribeRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *DescribeRequest) GetShowParams() []string {
	if m != nil {
		return m.ShowParams
	}
	return nil
}

type DescribeResponse struct {
	Api                  string         `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Cluster              *Cluster       `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Entrypoint           string         `protobuf:"bytes,3,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Config               *ClusterConfig `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Nodes                *ClusterNodes  `protobuf:"bytes,5,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Kubeconfig           string         `protobuf:"bytes,6,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DescribeResponse) Reset()         { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()    {}
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_257e39eedb50142f, []int{5}
}

func (m *DescribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeResponse.Unmarshal(m, b)
}
func (m *DescribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeResponse.Marshal(b, m, deterministic)
}
func (m *DescribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeResponse.Merge(m, src)
}
func (m *DescribeResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeResponse.Size(m)
}
func (m *DescribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeResponse proto.InternalMessageInfo

func (m *DescribeResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DescribeResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *DescribeResponse) GetEntrypoint() string {
	if m != nil {
		return m.Entrypoint
	}
	return ""
}

func (m *DescribeResponse) GetConfig() *ClusterConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *DescribeResponse) GetNodes() *ClusterNodes {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DescribeResponse) GetKubeconfig() string {
	if m != nil {
		return m.Kubeconfig
	}
	return ""
}

func init() {
	proto.RegisterEnum("kubekit.v1.DescribeLevel", DescribeLevel_name, DescribeLevel_value)
	proto.RegisterType((*ClusterConfig)(nil), "kubekit.v1.ClusterConfig")
	proto.RegisterMapType((map[string]string)(nil), "kubekit.v1.ClusterConfig.VariablesEntry")
	proto.RegisterType((*Node)(nil), "kubekit.v1.Node")
	proto.RegisterType((*NodePool)(nil), "kubekit.v1.NodePool")
	proto.RegisterType((*ClusterNodes)(nil), "kubekit.v1.ClusterNodes")
	proto.RegisterType((*DescribeRequest)(nil), "kubekit.v1.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "kubekit.v1.DescribeResponse")
}

func init() { proto.RegisterFile("describe.proto", fileDescriptor_257e39eedb50142f) }

var fileDescriptor_257e39eedb50142f = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x6c, 0x27, 0x69, 0x7c, 0xdd, 0xe4, 0xb3, 0x86, 0x2e, 0x4c, 0xf9, 0x69, 0xf0, 0x02,
	0x45, 0x48, 0x58, 0x4a, 0xba, 0x41, 0x88, 0x4d, 0x9b, 0xa4, 0xc5, 0x12, 0x4a, 0x2a, 0x17, 0x55,
	0x82, 0x4d, 0xe4, 0x24, 0x43, 0x6b, 0xc5, 0xf5, 0x0c, 0x33, 0xb6, 0x51, 0x5f, 0x81, 0xd7, 0xe1,
	0xdd, 0x58, 0xa3, 0x3b, 0x1e, 0x93, 0xa4, 0x0a, 0xbb, 0xf1, 0x39, 0xf7, 0x9c, 0x3b, 0xf7, 0x67,
	0x0c, 0xdd, 0x15, 0x95, 0x4b, 0x91, 0x2c, 0x68, 0xc0, 0x05, 0xcb, 0x19, 0x81, 0x75, 0xb1, 0xa0,
	0xeb, 0x24, 0x0f, 0xca, 0xc1, 0x71, 0x67, 0x99, 0x16, 0x32, 0xa7, 0xa2, 0xa2, 0xfc, 0x5f, 0x06,
	0x74, 0x46, 0x15, 0x32, 0x62, 0xd9, 0xb7, 0xe4, 0x96, 0x5c, 0x80, 0x5d, 0xc6, 0x22, 0x89, 0x17,
	0x29, 0x95, 0xde, 0x41, 0xcf, 0xea, 0x3b, 0xc3, 0x7e, 0xb0, 0x31, 0x08, 0x76, 0xa2, 0x83, 0x9b,
	0x3a, 0x74, 0x92, 0xe5, 0xe2, 0x21, 0xda, 0x48, 0xc9, 0x73, 0xb0, 0x05, 0x95, 0xac, 0x10, 0x4b,
	0x2a, 0xbd, 0x56, 0xcf, 0xea, 0xdb, 0xd1, 0x06, 0x38, 0xfe, 0x00, 0xdd, 0x5d, 0x29, 0x71, 0xc1,
	0x5a, 0xd3, 0x07, 0xcf, 0xe8, 0x19, 0x7d, 0x3b, 0xc2, 0x23, 0x39, 0x82, 0x66, 0x19, 0xa7, 0x05,
	0xf5, 0x4c, 0x85, 0x55, 0x1f, 0xef, 0xcd, 0x77, 0x86, 0xff, 0xd3, 0x84, 0xc6, 0x94, 0xad, 0x28,
	0x21, 0xd0, 0xc8, 0xe2, 0x7b, 0xaa, 0x55, 0xea, 0x4c, 0x9e, 0x81, 0xcd, 0x19, 0x4b, 0xe7, 0x8a,
	0xa8, 0xa4, 0x6d, 0x04, 0xa6, 0x9a, 0x14, 0x2c, 0xa5, 0x15, 0x69, 0x55, 0x24, 0x02, 0x35, 0xc9,
	0x8b, 0x45, 0x9a, 0x2c, 0xe7, 0x09, 0xf7, 0x1a, 0x5a, 0xa9, 0x80, 0x90, 0x93, 0x17, 0x00, 0x5c,
	0x24, 0x65, 0x9c, 0x53, 0x64, 0x9b, 0x8a, 0xb5, 0x35, 0x12, 0x72, 0xd4, 0xb2, 0xfc, 0x8e, 0x8a,
	0x79, 0xc2, 0xeb, 0x72, 0xdb, 0x0a, 0x08, 0xb9, 0x54, 0xda, 0xca, 0x78, 0x95, 0x61, 0x53, 0x2b,
	0xad, 0x42, 0xc6, 0x99, 0x24, 0x27, 0xe0, 0xd4, 0xd6, 0xc8, 0xb7, 0x15, 0x5f, 0x67, 0xc3, 0x80,
	0xbf, 0xe6, 0x48, 0xdb, 0x5b, 0xe6, 0xe3, 0x4c, 0xfa, 0x33, 0x68, 0x63, 0x2f, 0xae, 0x18, 0x4b,
	0x77, 0x6b, 0x37, 0x1e, 0xd5, 0xfe, 0x1a, 0x9a, 0x19, 0x5b, 0x51, 0xe9, 0x99, 0x6a, 0xaa, 0xee,
	0xf6, 0x54, 0xd1, 0x21, 0xaa, 0x68, 0x7f, 0x04, 0x87, 0x7a, 0xc8, 0x88, 0x4a, 0x72, 0x0a, 0x80,
	0xc4, 0x1c, 0x8d, 0xa4, 0x67, 0x28, 0xf1, 0xd1, 0x63, 0x31, 0xa6, 0x8f, 0xec, 0x4c, 0x9f, 0xa4,
	0x7f, 0x0b, 0xff, 0x8f, 0xf5, 0x16, 0x46, 0xf4, 0x7b, 0x41, 0x65, 0x8e, 0x13, 0x8e, 0x79, 0x52,
	0x4f, 0x38, 0xe6, 0x09, 0x79, 0x05, 0x87, 0x7a, 0x1d, 0xb7, 0xa7, 0xe5, 0x68, 0x4c, 0x5d, 0xfa,
	0x04, 0x1c, 0x79, 0xc7, 0x7e, 0xcc, 0x79, 0x2c, 0xe2, 0x7b, 0xe9, 0x59, 0xaa, 0x78, 0x40, 0xe8,
	0x4a, 0x21, 0xfe, 0x6f, 0x03, 0xdc, 0x4d, 0x26, 0xc9, 0x59, 0x26, 0xe9, 0x9e, 0x54, 0x6f, 0xe1,
	0x40, 0xdb, 0xaa, 0x2c, 0xce, 0xf0, 0xc9, 0x9e, 0xa5, 0x8e, 0xea, 0x18, 0xf2, 0x12, 0x80, 0xe2,
	0x5a, 0x72, 0x96, 0x64, 0xb9, 0x5e, 0x94, 0x2d, 0x84, 0x0c, 0xa0, 0xb5, 0x54, 0x2f, 0x40, 0xed,
	0x89, 0x33, 0x7c, 0xfa, 0xcf, 0x27, 0x12, 0xe9, 0x40, 0x12, 0xd4, 0xed, 0x6f, 0x2a, 0x85, 0xb7,
	0x47, 0xa1, 0xfa, 0xad, 0xc7, 0x80, 0x57, 0xc0, 0x08, 0x9d, 0xa6, 0x55, 0x5d, 0x61, 0x83, 0xbc,
	0x39, 0x83, 0x4e, 0x5d, 0xf7, 0x27, 0x5a, 0xd2, 0x94, 0xd8, 0xd0, 0x3c, 0x3f, 0xbb, 0x0e, 0x47,
	0xee, 0x7f, 0xa4, 0x0b, 0x30, 0xb9, 0x99, 0x44, 0x5f, 0x3e, 0x7f, 0x0c, 0xa7, 0x97, 0xae, 0x41,
	0x00, 0x5a, 0xa3, 0xd9, 0xf4, 0x22, 0xbc, 0x74, 0x4d, 0x0c, 0x9b, 0xce, 0xc6, 0x93, 0x6b, 0xd7,
	0x3a, 0x6f, 0x7c, 0x35, 0xcb, 0xc1, 0xa2, 0xa5, 0x7e, 0x05, 0xa7, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xd7, 0xbf, 0x74, 0xc1, 0x37, 0x04, 0x00, 0x00,
}
