// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_cluster.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetClustersRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Names                []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Filter               []string `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClustersRequest) Reset()         { *m = GetClustersRequest{} }
func (m *GetClustersRequest) String() string { return proto.CompactTextString(m) }
func (*GetClustersRequest) ProtoMessage()    {}
func (*GetClustersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad83cf3fa0f5577, []int{0}
}

func (m *GetClustersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClustersRequest.Unmarshal(m, b)
}
func (m *GetClustersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClustersRequest.Marshal(b, m, deterministic)
}
func (m *GetClustersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClustersRequest.Merge(m, src)
}
func (m *GetClustersRequest) XXX_Size() int {
	return xxx_messageInfo_GetClustersRequest.Size(m)
}
func (m *GetClustersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClustersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClustersRequest proto.InternalMessageInfo

func (m *GetClustersRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetClustersRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *GetClustersRequest) GetFilter() []string {
	if m != nil {
		return m.Filter
	}
	return nil
}

type GetClustersResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Clusters             []*Cluster `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClustersResponse) Reset()         { *m = GetClustersResponse{} }
func (m *GetClustersResponse) String() string { return proto.CompactTextString(m) }
func (*GetClustersResponse) ProtoMessage()    {}
func (*GetClustersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad83cf3fa0f5577, []int{1}
}

func (m *GetClustersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClustersResponse.Unmarshal(m, b)
}
func (m *GetClustersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClustersResponse.Marshal(b, m, deterministic)
}
func (m *GetClustersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClustersResponse.Merge(m, src)
}
func (m *GetClustersResponse) XXX_Size() int {
	return xxx_messageInfo_GetClustersResponse.Size(m)
}
func (m *GetClustersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClustersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClustersResponse proto.InternalMessageInfo

func (m *GetClustersResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetClustersResponse) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func init() {
	proto.RegisterType((*GetClustersRequest)(nil), "kubekit.v1.GetClustersRequest")
	proto.RegisterType((*GetClustersResponse)(nil), "kubekit.v1.GetClustersResponse")
}

func init() { proto.RegisterFile("get_cluster.proto", fileDescriptor_2ad83cf3fa0f5577) }

var fileDescriptor_2ad83cf3fa0f5577 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0x2d, 0x89,
	0x4f, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca,
	0x2e, 0x4d, 0x4a, 0xcd, 0xce, 0x2c, 0xd1, 0x2b, 0x33, 0x94, 0xe2, 0x45, 0x91, 0x52, 0x0a, 0xe1,
	0x12, 0x72, 0x4f, 0x2d, 0x71, 0x86, 0x88, 0x15, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0x09, 0x70, 0x31, 0x27, 0x16, 0x64, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42,
	0x22, 0x5c, 0xac, 0x79, 0x89, 0xb9, 0xa9, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x10,
	0x8e, 0x90, 0x18, 0x17, 0x5b, 0x5a, 0x66, 0x4e, 0x49, 0x6a, 0x91, 0x04, 0x0b, 0x58, 0x18, 0xca,
	0x53, 0x8a, 0xe0, 0x12, 0x46, 0x31, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x8b, 0xb1, 0xfa,
	0x5c, 0x1c, 0x50, 0xf7, 0x40, 0x4c, 0xe6, 0x36, 0x12, 0xd6, 0x43, 0x38, 0x56, 0x0f, 0x6a, 0x42,
	0x10, 0x5c, 0x91, 0x13, 0x4b, 0x14, 0x53, 0x99, 0x61, 0x12, 0x1b, 0xd8, 0xf1, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xed, 0x20, 0xb4, 0xf2, 0xec, 0x00, 0x00, 0x00,
}
