// Code generated by protoc-gen-go. DO NOT EDIT.
// source: init.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitRequest struct {
	Api                  string            `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Kind                 string            `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ClusterName          string            `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Platform             PlatformName      `protobuf:"varint,4,opt,name=platform,proto3,enum=kubekit.v1.PlatformName" json:"platform,omitempty"`
	Variables            map[string]string `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Credentials          map[string]string `protobuf:"bytes,6,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources            []string          `protobuf:"bytes,7,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *InitRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *InitRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *InitRequest) GetPlatform() PlatformName {
	if m != nil {
		return m.Platform
	}
	return PlatformName_UNKNOWN
}

func (m *InitRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *InitRequest) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *InitRequest) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type InitResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

func (m *InitResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *InitResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *InitResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "kubekit.v1.InitRequest")
	proto.RegisterMapType((map[string]string)(nil), "kubekit.v1.InitRequest.CredentialsEntry")
	proto.RegisterMapType((map[string]string)(nil), "kubekit.v1.InitRequest.VariablesEntry")
	proto.RegisterType((*InitResponse)(nil), "kubekit.v1.InitResponse")
}

func init() { proto.RegisterFile("init.proto", fileDescriptor_8d036da5b4a9bcf3) }

var fileDescriptor_8d036da5b4a9bcf3 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0x4d, 0xda, 0xdf, 0x2f, 0x93, 0x5a, 0xca, 0xe2, 0x61, 0x29, 0x1e, 0x62, 0x0f, 0x92,
	0x53, 0xa0, 0xd5, 0x83, 0x88, 0x78, 0xf0, 0x0f, 0xa8, 0x07, 0x91, 0x1c, 0x3c, 0x78, 0x91, 0x6d,
	0x3a, 0xc2, 0x92, 0x64, 0x13, 0x77, 0x37, 0x81, 0x7c, 0x35, 0x3f, 0x9d, 0x64, 0x93, 0x9a, 0x28,
	0x08, 0x7a, 0x9b, 0x9d, 0x79, 0xef, 0xed, 0xdb, 0x37, 0x0b, 0xc0, 0x05, 0xd7, 0x61, 0x21, 0x73,
	0x9d, 0x13, 0x48, 0xca, 0x0d, 0x26, 0x5c, 0x87, 0xd5, 0x6a, 0xb1, 0x17, 0xa7, 0xa5, 0xd2, 0x28,
	0xdb, 0xd1, 0xf2, 0xdd, 0x06, 0xef, 0x4e, 0x70, 0x1d, 0xe1, 0x5b, 0x89, 0x4a, 0x93, 0x39, 0xd8,
	0xac, 0xe0, 0xd4, 0xf2, 0xad, 0xc0, 0x8d, 0x9a, 0x92, 0x10, 0x70, 0x12, 0x2e, 0xb6, 0x74, 0x64,
	0x5a, 0xa6, 0x26, 0x87, 0x30, 0xed, 0x64, 0x5e, 0x04, 0xcb, 0x90, 0xda, 0x66, 0xe6, 0x75, 0xbd,
	0x07, 0x96, 0x21, 0x39, 0x81, 0xff, 0x45, 0xca, 0xf4, 0x6b, 0x2e, 0x33, 0xea, 0xf8, 0x56, 0x30,
	0x5b, 0xd3, 0xb0, 0xb7, 0x11, 0x3e, 0x76, 0xb3, 0x06, 0x1b, 0x7d, 0x22, 0xc9, 0x35, 0xb8, 0x15,
	0x93, 0x9c, 0x6d, 0x52, 0x54, 0x74, 0xec, 0xdb, 0x81, 0xb7, 0x3e, 0x1a, 0xd2, 0x06, 0x56, 0xc3,
	0xa7, 0x1d, 0xf0, 0x46, 0x68, 0x59, 0x47, 0x3d, 0x91, 0xdc, 0x83, 0x17, 0x4b, 0xdc, 0xa2, 0xd0,
	0x9c, 0xa5, 0x8a, 0x4e, 0x8c, 0x4e, 0xf0, 0x93, 0xce, 0x55, 0x0f, 0x6d, 0x95, 0x86, 0x64, 0x72,
	0x00, 0xae, 0x44, 0x95, 0x97, 0x32, 0x46, 0x45, 0xff, 0xf9, 0x76, 0xe0, 0x46, 0x7d, 0x63, 0x71,
	0x0e, 0xb3, 0xaf, 0x36, 0x9a, 0x00, 0x13, 0xac, 0x77, 0x01, 0x26, 0x58, 0x93, 0x7d, 0x18, 0x57,
	0x2c, 0x2d, 0xb1, 0x4b, 0xb0, 0x3d, 0x9c, 0x8d, 0x4e, 0xad, 0xc5, 0x05, 0xcc, 0xbf, 0x5f, 0xfe,
	0x17, 0xfe, 0xf2, 0x16, 0xa6, 0xed, 0x43, 0x54, 0x91, 0x0b, 0x85, 0xbf, 0x5c, 0x1e, 0x01, 0x67,
	0xb0, 0x34, 0x53, 0x5f, 0x3a, 0xcf, 0xa3, 0x6a, 0xb5, 0x99, 0x98, 0x3f, 0x71, 0xfc, 0x11, 0x00,
	0x00, 0xff, 0xff, 0x65, 0x59, 0x12, 0x5c, 0x3c, 0x02, 0x00, 0x00,
}
