// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenStatus struct {
	ExpirationTimestamp  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=expirationTimestamp,proto3" json:"expirationTimestamp,omitempty"`
	Token                string               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TokenStatus) Reset()         { *m = TokenStatus{} }
func (m *TokenStatus) String() string { return proto.CompactTextString(m) }
func (*TokenStatus) ProtoMessage()    {}
func (*TokenStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

func (m *TokenStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenStatus.Unmarshal(m, b)
}
func (m *TokenStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenStatus.Marshal(b, m, deterministic)
}
func (m *TokenStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenStatus.Merge(m, src)
}
func (m *TokenStatus) XXX_Size() int {
	return xxx_messageInfo_TokenStatus.Size(m)
}
func (m *TokenStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TokenStatus proto.InternalMessageInfo

func (m *TokenStatus) GetExpirationTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.ExpirationTimestamp
	}
	return nil
}

func (m *TokenStatus) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{1}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TokenRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *TokenRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type TokenResponse struct {
	Kind                 string          `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion           string          `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Spec                 *_struct.Struct `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *TokenStatus    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{2}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *TokenResponse) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *TokenResponse) GetSpec() *_struct.Struct {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *TokenResponse) GetStatus() *TokenStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenStatus)(nil), "kubekit.v1.TokenStatus")
	proto.RegisterType((*TokenRequest)(nil), "kubekit.v1.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "kubekit.v1.TokenResponse")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_3aff0bcd502840ab) }

var fileDescriptor_3aff0bcd502840ab = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0x80, 0x49, 0x9b, 0xbf, 0xd0, 0x49, 0x7f, 0x90, 0x55, 0x30, 0x14, 0xd1, 0xda, 0x53, 0x41,
	0x48, 0x69, 0x7d, 0x03, 0xcf, 0xe2, 0x61, 0x5b, 0x14, 0xbc, 0xc8, 0xb6, 0x8e, 0x65, 0x49, 0x93,
	0xdd, 0xee, 0xce, 0x16, 0x5f, 0xc7, 0x37, 0x95, 0x4e, 0x36, 0x5a, 0xd4, 0xdb, 0x64, 0xe6, 0x9b,
	0x6f, 0x26, 0xb3, 0x90, 0x91, 0x29, 0xb1, 0x2e, 0xac, 0x33, 0x64, 0x04, 0x94, 0x61, 0x85, 0xa5,
	0xa6, 0x62, 0x3f, 0x1b, 0x5e, 0x6c, 0x8c, 0xd9, 0x6c, 0x71, 0xca, 0x95, 0x55, 0x78, 0x9b, 0x7a,
	0x72, 0x61, 0x4d, 0x0d, 0x39, 0xbc, 0xfa, 0x59, 0x25, 0x5d, 0xa1, 0x27, 0x55, 0xd9, 0x06, 0x18,
	0xef, 0x20, 0x5b, 0x1e, 0xcc, 0x0b, 0x52, 0x14, 0xbc, 0xb8, 0x87, 0x53, 0x7c, 0xb7, 0xda, 0x29,
	0xd2, 0xa6, 0x5e, 0xb6, 0x6c, 0x9e, 0x8c, 0x92, 0x49, 0x36, 0x1f, 0x16, 0x8d, 0xad, 0x68, 0x6d,
	0xc5, 0x17, 0x21, 0xff, 0x6a, 0x13, 0x67, 0xf0, 0x8f, 0xd7, 0xce, 0x3b, 0xa3, 0x64, 0xd2, 0x97,
	0xcd, 0xc7, 0xf8, 0x09, 0x06, 0x3c, 0x52, 0xe2, 0x2e, 0xa0, 0x27, 0x71, 0x02, 0x5d, 0x65, 0x35,
	0xcf, 0xe8, 0xcb, 0x43, 0x28, 0xae, 0x61, 0xb0, 0xde, 0x06, 0x4f, 0xe8, 0x5e, 0x6a, 0x55, 0x61,
	0x6c, 0xcf, 0x62, 0xee, 0x41, 0x55, 0x28, 0x04, 0xa4, 0xce, 0x6c, 0x31, 0xef, 0x72, 0x89, 0xe3,
	0xf1, 0x47, 0x02, 0xff, 0xa3, 0xd9, 0x5b, 0x53, 0x7b, 0xa6, 0x4a, 0x5d, 0xbf, 0x46, 0x37, 0xc7,
	0xe2, 0x12, 0x40, 0x59, 0xfd, 0x88, 0xce, 0x6b, 0xd3, 0x6e, 0x76, 0x94, 0x11, 0x37, 0x90, 0x7a,
	0x8b, 0x6b, 0x36, 0x67, 0xf3, 0xf3, 0x5f, 0xff, 0xbc, 0xe0, 0xfb, 0x4a, 0x86, 0xc4, 0x14, 0x7a,
	0x9e, 0x2f, 0x97, 0xa7, 0x11, 0xff, 0x7e, 0x9a, 0xe2, 0xe8, 0xb0, 0x32, 0x62, 0x77, 0xe9, 0x73,
	0x67, 0x3f, 0x5b, 0xf5, 0xd8, 0x76, 0xfb, 0x19, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xfe, 0x45, 0xe7,
	0xd6, 0x01, 0x00, 0x00,
}
