// Code generated by protoc-gen-go. DO NOT EDIT.
// source: update.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateClusterRequest struct {
	Api                  string            `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Kind                 string            `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ClusterName          string            `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Variables            map[string]string `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Credentials          map[string]string `protobuf:"bytes,5,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources            []string          `protobuf:"bytes,6,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateClusterRequest) Reset()         { *m = UpdateClusterRequest{} }
func (m *UpdateClusterRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateClusterRequest) ProtoMessage()    {}
func (*UpdateClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f0fa214029f1c21, []int{0}
}

func (m *UpdateClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClusterRequest.Unmarshal(m, b)
}
func (m *UpdateClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClusterRequest.Marshal(b, m, deterministic)
}
func (m *UpdateClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClusterRequest.Merge(m, src)
}
func (m *UpdateClusterRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateClusterRequest.Size(m)
}
func (m *UpdateClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClusterRequest proto.InternalMessageInfo

func (m *UpdateClusterRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateClusterRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *UpdateClusterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *UpdateClusterRequest) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *UpdateClusterRequest) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *UpdateClusterRequest) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type UpdateClusterResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateClusterResponse) Reset()         { *m = UpdateClusterResponse{} }
func (m *UpdateClusterResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateClusterResponse) ProtoMessage()    {}
func (*UpdateClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f0fa214029f1c21, []int{1}
}

func (m *UpdateClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClusterResponse.Unmarshal(m, b)
}
func (m *UpdateClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClusterResponse.Marshal(b, m, deterministic)
}
func (m *UpdateClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClusterResponse.Merge(m, src)
}
func (m *UpdateClusterResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateClusterResponse.Size(m)
}
func (m *UpdateClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClusterResponse proto.InternalMessageInfo

func (m *UpdateClusterResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateClusterRequest)(nil), "kubekit.v1.UpdateClusterRequest")
	proto.RegisterMapType((map[string]string)(nil), "kubekit.v1.UpdateClusterRequest.CredentialsEntry")
	proto.RegisterMapType((map[string]string)(nil), "kubekit.v1.UpdateClusterRequest.VariablesEntry")
	proto.RegisterType((*UpdateClusterResponse)(nil), "kubekit.v1.UpdateClusterResponse")
}

func init() { proto.RegisterFile("update.proto", fileDescriptor_3f0fa214029f1c21) }

var fileDescriptor_3f0fa214029f1c21 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xc9, 0x9f, 0x16, 0x32, 0x29, 0x52, 0x96, 0x0a, 0x4b, 0xf1, 0x10, 0x7b, 0x8a, 0x97,
	0x48, 0xf4, 0x22, 0x22, 0x1e, 0x2c, 0x1e, 0xf5, 0x10, 0xd1, 0x83, 0x17, 0xd9, 0x24, 0x73, 0x08,
	0x9b, 0x6e, 0xe2, 0xfe, 0x09, 0xe4, 0xd3, 0xf8, 0x55, 0xa5, 0x9b, 0x96, 0x68, 0x15, 0xc4, 0xdb,
	0xec, 0x1b, 0xde, 0x6f, 0x66, 0xdf, 0xc0, 0xcc, 0xb4, 0x25, 0xd3, 0x98, 0xb4, 0xb2, 0xd1, 0x0d,
	0x01, 0x6e, 0x72, 0xe4, 0x95, 0x4e, 0xba, 0x74, 0xf5, 0xe1, 0xc1, 0xe2, 0xd9, 0x36, 0xd7, 0xb5,
	0x51, 0x1a, 0x65, 0x86, 0xef, 0x06, 0x95, 0x26, 0x73, 0xf0, 0x58, 0x5b, 0x51, 0x27, 0x72, 0xe2,
	0x20, 0xdb, 0x96, 0x84, 0x80, 0xcf, 0x2b, 0x51, 0x52, 0xd7, 0x4a, 0xb6, 0x26, 0xa7, 0x30, 0x2b,
	0x06, 0xdf, 0x9b, 0x60, 0x1b, 0xa4, 0x9e, 0xed, 0x85, 0x3b, 0xed, 0x91, 0x6d, 0x90, 0x3c, 0x40,
	0xd0, 0x31, 0x59, 0xb1, 0xbc, 0x46, 0x45, 0xfd, 0xc8, 0x8b, 0xc3, 0x8b, 0xf3, 0x64, 0xdc, 0x20,
	0xf9, 0x6d, 0x7a, 0xf2, 0xb2, 0x77, 0xdc, 0x0b, 0x2d, 0xfb, 0x6c, 0x24, 0x90, 0x27, 0x08, 0x0b,
	0x89, 0x25, 0x0a, 0x5d, 0xb1, 0x5a, 0xd1, 0x89, 0x05, 0xa6, 0x7f, 0x02, 0xd7, 0xa3, 0x67, 0x40,
	0x7e, 0xa5, 0x90, 0x13, 0x08, 0x24, 0xaa, 0xc6, 0xc8, 0x02, 0x15, 0x9d, 0x46, 0x5e, 0x1c, 0x64,
	0xa3, 0xb0, 0xbc, 0x81, 0xa3, 0xef, 0xfb, 0x6c, 0xc3, 0xe1, 0xd8, 0xef, 0xc3, 0xe1, 0xd8, 0x93,
	0x05, 0x4c, 0x3a, 0x56, 0x1b, 0xdc, 0xa5, 0x33, 0x3c, 0xae, 0xdd, 0x2b, 0x67, 0x79, 0x0b, 0xf3,
	0xc3, 0xe1, 0xff, 0xf1, 0xaf, 0xce, 0xe0, 0xf8, 0xe0, 0x47, 0xaa, 0x6d, 0x84, 0xc2, 0x9f, 0x17,
	0xba, 0xf3, 0x5f, 0xdd, 0x2e, 0xcd, 0xa7, 0xf6, 0xca, 0x97, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0xe5, 0x7b, 0xbc, 0xf5, 0x01, 0x00, 0x00,
}
