// Code generated by protoc-gen-go. DO NOT EDIT.
// source: version.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersionRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{0}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

func (m *VersionRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type VersionResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Kubekit              string   `protobuf:"bytes,2,opt,name=kubekit,proto3" json:"kubekit,omitempty"`
	Kubernetes           string   `protobuf:"bytes,3,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	Docker               string   `protobuf:"bytes,4,opt,name=docker,proto3" json:"docker,omitempty"`
	Etcd                 string   `protobuf:"bytes,5,opt,name=etcd,proto3" json:"etcd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d2c07d79758f814, []int{1}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *VersionResponse) GetKubekit() string {
	if m != nil {
		return m.Kubekit
	}
	return ""
}

func (m *VersionResponse) GetKubernetes() string {
	if m != nil {
		return m.Kubernetes
	}
	return ""
}

func (m *VersionResponse) GetDocker() string {
	if m != nil {
		return m.Docker
	}
	return ""
}

func (m *VersionResponse) GetEtcd() string {
	if m != nil {
		return m.Etcd
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "kubekit.v1.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "kubekit.v1.VersionResponse")
}

func init() { proto.RegisterFile("version.proto", fileDescriptor_7d2c07d79758f814) }

var fileDescriptor_7d2c07d79758f814 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4b, 0x2d, 0x2a,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0x2e, 0x4d, 0x4a, 0xcd,
	0xce, 0x2c, 0xd1, 0x2b, 0x33, 0x54, 0x52, 0xe2, 0xe2, 0x0b, 0x83, 0x48, 0x06, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0x27, 0x16, 0x64, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x81, 0x98, 0x4a, 0x9d, 0x8c, 0x5c, 0xfc, 0x70, 0x45, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x98, 0xaa, 0x84, 0x24, 0xb8, 0xd8, 0xa1, 0xe6, 0x4a, 0x30, 0x81, 0x45, 0x61, 0x5c, 0x21, 0x39,
	0x2e, 0xb0, 0x8d, 0x45, 0x79, 0xa9, 0x25, 0xa9, 0xc5, 0x12, 0xcc, 0x60, 0x49, 0x24, 0x11, 0x21,
	0x31, 0x2e, 0xb6, 0x94, 0xfc, 0xe4, 0xec, 0xd4, 0x22, 0x09, 0x16, 0xb0, 0x1c, 0x94, 0x27, 0x24,
	0xc4, 0xc5, 0x92, 0x5a, 0x92, 0x9c, 0x22, 0xc1, 0x0a, 0x16, 0x05, 0xb3, 0x9d, 0x58, 0xa2, 0x98,
	0xca, 0x0c, 0x93, 0xd8, 0xc0, 0x1e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x03, 0xc4,
	0x37, 0xd9, 0x00, 0x00, 0x00,
}
